### ISSUE TITLE
couldn't run 

### ISSUE THREAD

**Issue by ishakya** [imomin/angular-fullstack-multi-tenant#1]
Getting this error:

500 TypeError: Cannot read property 'Client' of undefined
at Layer.handle (/home/isha/work/Yo/server/components/multitenant/setClientDb.js:6:81)
at trim_prefix (/home/isha/work/Yo/node_modules/express/lib/router/index.js:226:17)
at c (/home/isha/work/Yo/node_modules/express/lib/router/index.js:198:9)
at Function.proto.process_params (/home/isha/work/Yo/node_modules/express/lib/router/index.js:251:12)
at next (/home/isha/work/Yo/node_modules/express/lib/router/index.js:189:19)
at Layer.handle (/home/isha/work/Yo/server/components/multitenant/clientListener.js:15:9)
at trim_prefix (/home/isha/work/Yo/node_modules/express/lib/router/index.js:226:17)
at c (/home/isha/work/Yo/node_modules/express/lib/router/index.js:198:9)
at Function.proto.process_params (/home/isha/work/Yo/node_modules/express/lib/router/index.js:251:12)
at next (/home/isha/work/Yo/node_modules/express/lib/router/index.js:189:19)
at Layer.initialize [as handle](/home/isha/work/Yo/node_modules/passport/lib/middleware/initialize.js:62:5)
at trim_prefix (/home/isha/work/Yo/node_modules/express/lib/router/index.js:226:17)
at c (/home/isha/work/Yo/node_modules/express/lib/router/index.js:198:9)
at Function.proto.process_params (/home/isha/work/Yo/node_modules/express/lib/router/index.js:251:12)
at next (/home/isha/work/Yo/node_modules/express/lib/router/index.js:189:19)
at Layer.cookieParser [as handle](/home/isha/work/Yo/node_modules/cookie-parser/index.js:46:5)

**Comment by imomin** [comment]
I am assuming you went through process of installing dependency packages.
I was trying achieve http:\test.example.com and http:\test2.example.com
both with different database. I updated the host file had the subdomain
point to localhost IP (127.0.0.1).

You will need to go to the site using subdomain and not http:\localhost.

**Comment by ishakya** [comment]
I tried running it using subdomain but couldn't run it.

**Comment by imomin** [comment]
Getting any errors?

**Comment by ishakya** [comment]
I got no errors but the return functions inside the middlewares(i.e clientListener middleware, setClientDb middleware, databaseModels middleware and  setClientSocket  middleware) are not being called. I have no idea why this is happening.

**Comment by ishakya** [comment]
Even when i shifted them in express.js still they are not being called.

**Comment by ishakya** [comment]
var domain = req.headers.host,
subDomain = domain.split('.'); 
i used this subDomain[0] instead of req.subdomains[0].
